// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpIB9oNdO15y23LI0zCld-FPCWIIiHteU',
    appId: '1:5182096725:web:77fb1abeaa6b3d9b57dbdc',
    messagingSenderId: '5182096725',
    projectId: 'intentions-dbc94',
    authDomain: 'intentions-dbc94.firebaseapp.com',
    storageBucket: 'intentions-dbc94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAd_xLixC2bLb0Tc-T7Ya-M32KNX4LbFo',
    appId: '1:5182096725:android:554fad0ba5d9e17357dbdc',
    messagingSenderId: '5182096725',
    projectId: 'intentions-dbc94',
    storageBucket: 'intentions-dbc94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXDYRkBq8A7DJawfXmQZC_NohilaP9zU',
    appId: '1:5182096725:ios:1f1116e86a9c1e8957dbdc',
    messagingSenderId: '5182096725',
    projectId: 'intentions-dbc94',
    storageBucket: 'intentions-dbc94.firebasestorage.app',
    iosBundleId: 'com.example.intentionsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXDYRkBq8A7DJawfXmQZC_NohilaP9zU',
    appId: '1:5182096725:ios:1f1116e86a9c1e8957dbdc',
    messagingSenderId: '5182096725',
    projectId: 'intentions-dbc94',
    storageBucket: 'intentions-dbc94.firebasestorage.app',
    iosBundleId: 'com.example.intentionsFlutter',
  );
}
